// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComplaintDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complaint_date");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complaint_type");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("complaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplaintDate = new DateTime(2026, 9, 2, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5449),
                            ComplaintType = "Overcharging",
                            ContactNumber = "0711234567",
                            CreatedAt = new DateTime(2026, 9, 2, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5456),
                            Description = "The conductor charged Rs. 150 for a ticket that should have been Rs. 100. Did not provide a ticket.",
                            Location = "Nugegoda",
                            RouteNumber = "138",
                            Status = "Pending",
                            UpdatedAt = new DateTime(2026, 9, 2, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5457)
                        },
                        new
                        {
                            Id = 2,
                            ComplaintDate = new DateTime(2026, 8, 30, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5459),
                            ComplaintType = "Overcrowding",
                            CreatedAt = new DateTime(2026, 8, 30, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5460),
                            Description = "The bus was extremely overcrowded during evening rush hour. People were hanging from the footboard.",
                            Location = "Piliyandala",
                            RouteNumber = "120",
                            Status = "Under Review",
                            UpdatedAt = new DateTime(2026, 9, 3, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5461)
                        },
                        new
                        {
                            Id = 3,
                            ComplaintDate = new DateTime(2026, 8, 25, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5462),
                            ComplaintType = "Reckless Driving",
                            ContactNumber = "0777654321",
                            CreatedAt = new DateTime(2026, 8, 25, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5463),
                            Description = "Driver was racing with another bus and almost hit a pedestrian near the campus.",
                            Location = "Moratuwa",
                            RouteNumber = "255",
                            Status = "Resolved",
                            UpdatedAt = new DateTime(2026, 9, 1, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5464)
                        },
                        new
                        {
                            Id = 4,
                            ComplaintDate = new DateTime(2026, 9, 3, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5465),
                            ComplaintType = "Bus Did Not Stop",
                            CreatedAt = new DateTime(2026, 9, 3, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5466),
                            Description = "Waited at the halt for 45 minutes. Three buses passed but none stopped despite having space.",
                            Location = "Bambalapitiya",
                            RouteNumber = "101",
                            Status = "Pending",
                            UpdatedAt = new DateTime(2026, 9, 3, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5466)
                        },
                        new
                        {
                            Id = 5,
                            ComplaintDate = new DateTime(2026, 8, 31, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5468),
                            ComplaintType = "Poor Staff Behaviour",
                            CreatedAt = new DateTime(2026, 8, 31, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5469),
                            Description = "Conductor was extremely rude when asked to return the balance money.",
                            Location = "Fort",
                            RouteNumber = "100",
                            Status = "Under Review",
                            UpdatedAt = new DateTime(2026, 9, 2, 5, 0, 54, 141, DateTimeKind.Utc).AddTicks(5469)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
